import type { ProviderCatalog } from './types.js';

const zeroCost = {
  input: 0,
  output: 0,
  cache_read: 0,
  cache_write: 0,
};

export const builtinProviderCatalog: ProviderCatalog = {
  provider: {
    openai: {
      name: 'OpenAI',
      enabled: true,
      kind: 'openai',
      api_key_env: 'OPENAI_API_KEY',
      base_url: 'https://api.openai.com/v1',
      headers: {},
      options: {},
    },
    anthropic: {
      name: 'Anthropic',
      enabled: true,
      kind: 'anthropic',
      api_key_env: 'ANTHROPIC_API_KEY',
      headers: {},
      options: {},
    },
  },
  models: {
    openai: {
      'gpt-5.5': {
        provider: 'openai',
        api_id: 'gpt-5.5',
        endpoint: 'responses',
        status: 'active',
        context: 400_000,
        output: 32_000,
        cost: zeroCost,
        reasoning: true,
        temperature: false,
        tool_call: true,
        input_modalities: ['text', 'image', 'pdf'],
        output_modalities: ['text'],
        headers: {},
        options: {},
        variants: {
          none: { reasoningEffort: 'none' },
          low: { reasoningEffort: 'low' },
          medium: { reasoningEffort: 'medium' },
          high: { reasoningEffort: 'high' },
          xhigh: { reasoningEffort: 'xhigh' },
        },
      },
      'gpt-5.4': {
        provider: 'openai',
        api_id: 'gpt-5.4',
        endpoint: 'responses',
        status: 'active',
        context: 400_000,
        output: 32_000,
        cost: zeroCost,
        reasoning: true,
        temperature: false,
        tool_call: true,
        input_modalities: ['text', 'image', 'pdf'],
        output_modalities: ['text'],
        headers: {},
        options: {},
        variants: {
          none: { reasoningEffort: 'none' },
          low: { reasoningEffort: 'low' },
          medium: { reasoningEffort: 'medium' },
          high: { reasoningEffort: 'high' },
        },
      },
    },
    anthropic: {
      'claude-opus-4.8': {
        provider: 'anthropic',
        api_id: 'claude-opus-4.8',
        status: 'active',
        context: 200_000,
        output: 64_000,
        cost: zeroCost,
        reasoning: true,
        temperature: true,
        tool_call: true,
        input_modalities: ['text', 'image', 'pdf'],
        output_modalities: ['text'],
        headers: {},
        options: {},
        variants: {
          low: { reasoningEffort: 'low' },
          medium: { reasoningEffort: 'medium' },
          high: { reasoningEffort: 'high' },
        },
      },
      'claude-opus-4.7': {
        provider: 'anthropic',
        api_id: 'claude-opus-4.7',
        status: 'active',
        context: 200_000,
        output: 64_000,
        cost: zeroCost,
        reasoning: true,
        temperature: true,
        tool_call: true,
        input_modalities: ['text', 'image', 'pdf'],
        output_modalities: ['text'],
        headers: {},
        options: {},
        variants: {
          low: { reasoningEffort: 'low' },
          medium: { reasoningEffort: 'medium' },
          high: { reasoningEffort: 'high' },
        },
      },
      'claude-opus-4.6': {
        provider: 'anthropic',
        api_id: 'claude-opus-4.6',
        status: 'active',
        context: 200_000,
        output: 64_000,
        cost: zeroCost,
        reasoning: true,
        temperature: true,
        tool_call: true,
        input_modalities: ['text', 'image', 'pdf'],
        output_modalities: ['text'],
        headers: {},
        options: {},
        variants: {
          low: { reasoningEffort: 'low' },
          medium: { reasoningEffort: 'medium' },
          high: { reasoningEffort: 'high' },
        },
      },
      'claude-sonnet-4.6': {
        provider: 'anthropic',
        api_id: 'claude-sonnet-4.6',
        status: 'active',
        context: 200_000,
        output: 64_000,
        cost: zeroCost,
        reasoning: true,
        temperature: true,
        tool_call: true,
        input_modalities: ['text', 'image', 'pdf'],
        output_modalities: ['text'],
        headers: {},
        options: {},
        variants: {
          low: { reasoningEffort: 'low' },
          medium: { reasoningEffort: 'medium' },
          high: { reasoningEffort: 'high' },
        },
      },
      'claude-haiku-4.5': {
        provider: 'anthropic',
        api_id: 'claude-haiku-4.5',
        status: 'active',
        context: 200_000,
        output: 32_000,
        cost: zeroCost,
        reasoning: true,
        temperature: true,
        tool_call: true,
        input_modalities: ['text', 'image', 'pdf'],
        output_modalities: ['text'],
        headers: {},
        options: {},
        variants: {
          low: { reasoningEffort: 'low' },
          medium: { reasoningEffort: 'medium' },
        },
      },
    },
  },
  profile: {
    main: {
      label: 'Main',
      description: '高质量编码任务的默认模型套件。',
      models: {
        primary: 'openai/gpt-5.5',
        small: 'openai/gpt-5.4',
        compact: 'openai/gpt-5.4',
        title: 'openai/gpt-5.4',
        review: 'anthropic/claude-sonnet-4.6',
      },
      settings: {
        primary: { reasoning_effort: 'medium' },
        small: { reasoning_effort: 'low' },
        compact: { reasoning_effort: 'low' },
        title: { reasoning_effort: 'low' },
        review: { reasoning_effort: 'high' },
      },
    },
    anthropic: {
      label: 'Anthropic',
      description: '偏向 Anthropic 的编码与审查模型套件。',
      models: {
        primary: 'anthropic/claude-sonnet-4.6',
        small: 'anthropic/claude-haiku-4.5',
        compact: 'anthropic/claude-haiku-4.5',
        title: 'anthropic/claude-haiku-4.5',
        review: 'anthropic/claude-opus-4.8',
      },
      settings: {
        primary: { reasoning_effort: 'medium' },
        small: { reasoning_effort: 'low' },
        compact: { reasoning_effort: 'low' },
        title: { reasoning_effort: 'low' },
        review: { reasoning_effort: 'high' },
      },
    },
  },
};
