/**
 * config 模块的公开出口。
 *
 * 外部模块只从这里导入配置能力，避免直接依赖 loader/schema/paths 的内部文件布局。
 */
export {
  ensureBuiltinAssets,
  ensureElloHome,
  ensureGlobalConfig,
  ensureProjectConfig,
} from './initializer.js';
export {
  deleteConfigValues,
  getConfigValue,
  getProjectConfigPath,
  loadCodingAgentConfig,
  loadConfigSources,
  setConfigValue,
  setConfigValues,
  writeConfigPath,
  ConfigValidationError,
  type ConfigSourceName,
  type LoadedConfigSource,
  type WritableConfigSourceName,
} from './loader.js';
export {
  globalAgentsDir,
  globalCacheDir,
  globalConfigPath,
  globalGitignorePath,
  globalHomeDir,
  globalLogsDir,
  globalMcpPath,
  globalSessionsDir,
  globalSkillsDir,
  projectAgentsDir,
  projectConfigPath,
  projectElloDir,
  projectPermissionsFile,
  projectSkillsDir,
  userPermissionsFile,
} from './paths.js';
export {
  AgentConfigSchema,
  AgentModeSchema,
  AgentRoleSchema,
  CodingAgentConfigSchema,
  GoalConfigSchema,
  LangfuseObservabilityConfigSchema,
  ObservabilityConfigSchema,
  ModelCatalogEntrySchema,
  ModelRoleSettingsSchema,
  PermissionRuleSchema,
  ProfileSuiteSchema,
  ProviderConnectionSchema,
  ToolConfigSchema,
  WorkspaceConfigSchema,
  type AgentConfigEntry,
  type CodingAgentConfig,
  type CodingAgentConfigOverrides,
  type GoalConfig,
  type LangfuseObservabilityConfig,
  type LangfuseTracingConfig,
  type ObservabilityConfig,
  type ModelCatalogEntryConfig,
  type ModelRoleSettingsConfig,
  type PermissionRule,
  type ProfileSuiteConfig,
  type ProviderConnectionConfig,
  type ToolConfig,
  type WorkspaceConfig,
} from './schema.js';
